In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('50_Startups.csv')

In [3]:
#dataset

In [4]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [5]:
#datasets

In [6]:
independent=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=datasets[['Profit']]

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size =0.30, random_state = 0)

In [8]:
#standardizing the input training and test set
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor=regressor.fit(X_train,y_train)

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [12]:
r_score

0.0067683444800727965

In [14]:
import pickle
filename="finalModel_SVM.sav"
pickle.dump(regressor,open(filename,"wb"))

In [15]:
# Preprocessing the input 
preinput=sc.transform([[1300,12000,4000,0,1]])
preinput

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.46755405, -4.33835385, -1.50744257, -0.5       ,  1.30088727]])

In [16]:
loaded_model=pickle.load(open("finalModel_SVM.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([107679.41510409])

In [53]:
rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))

R&D:2000
Admin400
Marketing 4000
State_flo 0 or 1:0
State_new 0 or 1:0


In [54]:
result=regressor.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

C:\Anaconda3\envs\ML\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"


In [55]:
result

array([42943.67266674])