In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('50_Startups.csv')

In [3]:
#dataset

In [4]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [5]:
#datasets

In [6]:
independent=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=datasets[['Profit']]

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size =0.30, random_state = 0)

In [8]:
#standardizing the input training and test set
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train.values)
X_test = sc.transform(X_test.values)

#standardizing the output training and test set
from sklearn.preprocessing import StandardScaler
scy = StandardScaler()
y_train = scy.fit_transform(y_train)
y_test = scy.transform(y_test)


In [9]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor=regressor.fit(X_train,y_train.ravel())

In [10]:
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [12]:
r_score

0.6352566974206106

In [13]:
import pickle
filename="finalModel_SVM_Preprocessed.sav"
pickle.dump(regressor,open(filename,"wb"))
## Actual code ends here ###

In [14]:
# Testing the preprocessed the input - This code not required in actual development
# Only for testing purpose the below code is executed
# Inorder to compare with the DeployModel - 
preinput=sc.transform([[1300,12000,4000,0,1]])
preinput


array([[-1.46755405, -4.33835385, -1.50744257, -0.5       ,  1.30088727]])

In [15]:
loaded_model=pickle.load(open("finalModel_SVM_Preprocessed.sav",'rb'))
result=loaded_model.predict(preinput)
## Prediction processed output
result

array([-1.03109284])

In [16]:
## Transforming the processed o/p to preprocessed output
preOutput=scy.inverse_transform([result])
preOutput

array([[65875.16964031]])